routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Teacher\TeacherHomeController;
use App\Http\Controllers\Teacher\PaperController;
use App\Http\Controllers\Teacher\StudentController;
use App\Http\Controllers\Teacher\LaunchQuizController;
use App\Http\Controllers\Admin\SubAdminController;
use App\Http\Controllers\TraineeController;
use Illuminate\Support\Facades\Auth;
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('frontend.index');
    //return view('welcome');
});
/*Route::get('paywithpaypal', [\App\Http\Controllers\PaymentController::class,'payWithPaypal'])->name('paywithpaypal');
Route::post('paypal', [\App\Http\Controllers\PaymentController::class,'postPaymentWithpaypal'])->name('paypal');
Route::get('paypal', [\App\Http\Controllers\PaymentController::class,'getPaymentStatus'])->name('status');*/
/*==================paypal route===============*/
Route::get('/execute-payment', [\App\Http\Controllers\PaymentController::class,'execute']);
Route::post('/create-payment',[ \App\Http\Controllers\PaymentController::class,'create'])->name('create-payment');

Route::get('plan/create',[\App\Http\Controllers\SubscriptionController::class,'createPlan']);

Route::get('plan/list',[\App\Http\Controllers\SubscriptionController::class,'listPlan']);
Route::get('plan/{id}',[\App\Http\Controllers\SubscriptionController::class,'showPlan']);
Route::get('plan/{id}/activate',[\App\Http\Controllers\SubscriptionController::class,'activatePlan']);

Route::post('plan/{id}/agreement/create',[\App\Http\Controllers\SubscriptionController::class,'createAgreement'])->name('create-agreement');
Route::get('execute-agreement/{success}',[\App\Http\Controllers\SubscriptionController::class,'executeAgreement']);
/*==================paypal route===============*/

/*Route::get('payment', [\App\Http\Controllers\PayPalController::class,'payment'])->name('payment');
Route::get('cancel',  [\App\Http\Controllers\PayPalController::class,'cancel'])->name('payment.cancel');
Route::get('payment/success', [\App\Http\Controllers\PayPalController::class,'success'])->name('payment.success');*/

Route::get('/verify/{user}/{token}', [\App\Http\Controllers\Auth\RegisterController::class, 'verifyUser'])->name('verify');
Route::get('trianer/dashboard', [\App\Http\Controllers\Auth\RegisterController::class, 'trainerDashboard'])->name('trianer.dashboard');
Route::post('user/logout', [HomeController::class, 'logOutUser'])->name('logout.user');
Auth::routes();

Route::group(['prefix' => 'trainer'], function () {
    Route::get('/login', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'showLoginForm'])->name('teacher.login');
    Route::post('/login', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'TeacherLogin'])->name('teacher.login.submit');
    Route::post('/logout', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'logout'])->name('teacher.logout');
    Route::get('/register', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'showRegisterForm'])->name('teacher.register');
    Route::post('/register', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'TeacherRegister'])->name('teacher.register.store');
    Route::get('/V65Z2wb7qOFrwsBvJ2yxlxh6Cr99mXPAzdaRHJpFZO3N5isIyXzH9iCdWScM', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'basicPackage'])->name('basic.package');
    Route::get('/dbWuKajpRkewL6H79AStw3dhg57pCptYFSPdLqMi2KShbgzNYbcZKst10SkC', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'premiumPackage'])->name('premium.package');
});

Route::group(['middleware' => ['auth:teacher'],'prefix' => 'trainer'], function () {
    Route::get('/', [TeacherHomeController::class, 'index'])->name('teacher.home');
    Route::get('/success', [TeacherHomeController::class, 'success'])->name('success');
    Route::get('/return', [TeacherHomeController::class, 'failure'])->name('failure');
    //Route::middleware([\App\Http\Middleware\Subscription::class])->group(function(){
        Route::resource('question', \App\Http\Controllers\Teacher\QuestionController::class);
        Route::resource('classrooms', \App\Http\Controllers\Teacher\ClassRoomController::class);
        Route::resource('students', StudentController::class);
        Route::get('all/trainee/{id}', [StudentController::class,'index'])->name('all.trainee');
        Route::get('create/trainee/{id}', [StudentController::class,'createTrainee'])->name('create.trainee');
        Route::get('edit/trainee/{id}', [StudentController::class,'editTrainee'])->name('edit.trainee');
        Route::post('save/trainee/{id}', [StudentController::class,'storeTrainee'])->name('save.trainee');
        Route::post('update/trainee/{id}', [StudentController::class,'updateTrainee'])->name('update.trainee');
        Route::delete('delete/trainee/{id}', [StudentController::class, 'destroy'])->name('trainer.trainee.destroy');
        Route::resource('quiz', PaperController::class);
        Route::get('/result', [PaperController::class, 'result'])->name('result.quiz');
        Route::get('/archive', [PaperController::class, 'archive'])->name('archive.quiz');
        Route::post('archive/status/{id}', [LaunchQuizController::class, 'QuizPutToArchive'])->name('putarchive');
        Route::post('archive/revert/{id}', [LaunchQuizController::class, 'archiveRevrt'])->name('archive.revert');
        Route::get('get/options', [PaperController::class, 'getQuestionOptions'])->name('getoption');
        Route::resource('launch', LaunchQuizController::class);
        Route::get('/quiz/attempt/{id}', [LaunchQuizController::class, 'attemptQuiz'])->name('quizattempt');
        Route::get('/course/result/{id}/{classroom}', [LaunchQuizController::class, 'trineeResult'])->name('trainee.result');
        Route::post('/course/end/{id}', [LaunchQuizController::class, 'courseEnd'])->name('course.end');
        Route::get('/course/result-table/{id}/{classroom}', [LaunchQuizController::class, 'trineeResultTable'])->name('trainee.resultTable');
        Route::get('/profile', [TeacherHomeController::class, 'editProfile'])->name('profile.edit');
        Route::post('/profile/edit', [TeacherHomeController::class, 'profileUpdate'])->name('profile.update');
        Route::get('/subscription/plan', [TeacherHomeController::class, 'subscriptionPlan'])->name('subs.plan');
        Route::get('get/trainee', [PaperController::class, 'getTrainee'])->name('get.traine');
    //});
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'adminLogin'])->name('admin.login.submit');
    Route::post('/logout', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('admin.logout');
});

Route::group(['middleware' => ['auth:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin.home');
    Route::resource('subadmin', SubAdminController::class);
    Route::resource('teacher', \App\Http\Controllers\Admin\TeacherController::class);
    Route::get('/profile', [\App\Http\Controllers\Admin\HomeController::class, 'editProfile'])->name('admin.edit.profile');
    Route::post('/profile', [\App\Http\Controllers\Admin\HomeController::class, 'updateProfile'])->name('admin.update.profile');
    // for Students
    Route::resource('student', \App\Http\Controllers\Admin\StudentsController::class);
    Route::resource('classroom', \App\Http\Controllers\Admin\ClassRoomController::class);
    // for Students
    Route::get('/quiz', [\App\Http\Controllers\Admin\StudentController::class, 'papers'])->name('quiz.all');
    Route::get('/transaction', [\App\Http\Controllers\Admin\HomeController::class, 'transaction'])->name('transaction');
    Route::get('/packages', [\App\Http\Controllers\Admin\HomeController::class, 'packages'])->name('package');
    Route::post('update/packages', [\App\Http\Controllers\Admin\HomeController::class, 'updatePackages'])->name('update.package');
    Route::get('/launch/quiz', [\App\Http\Controllers\Admin\StudentController::class, 'launchPapers'])->name('admin.launch.quiz');
    Route::delete('/delete/paper', [\App\Http\Controllers\Admin\StudentController::class, 'deletePaper'])->name('admin.paper.destroy');
});

Route::group(['prefix' => 'subadmin'], function () {
    Route::get('/login', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'showLoginForm'])->name('subadmin.login');
    Route::post('/login', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'subAdminLogin'])->name('subadmin.login.submit');
    Route::post('/logout', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'logout'])->name('subadmin.logout');
    Route::get('/register', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'showRegisterForm'])->name('subadmin.register');
    Route::post('/register', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'subAdminRegister'])->name('subadmin.register.store');
    Route::post('/verify', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'subAdminRegister'])->name('subadmin.register.verify');
});

Route::group(['middleware' => ['auth:subadmin'], 'prefix' => 'subadmin'], function () {
    Route::get('/', [\App\Http\Controllers\SubAdmin\HomeController::class, 'index'])->name('subadmin.home');

app/Models/Teacher.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class Teacher extends Authenticatable
{
    use HasFactory, Notifiable;
    protected $guarded = [];
    protected $guard = 'teacher';

    public function subAdmin() {
        return $this->belongsTo(SubAdmin::class);
    }

    public function students() {
        return $this->hasMany(User::class);
    }

    public function quiz() {
        return $this->hasMany(LaunchQuiz::class);
    }
    public function traineeGroups() {
        return $this->hasMany(ClassRoom::class);
    }
    public function transactions() {
        return $this->hasMany(Transanction::class,'payer_id');
    }
    public function latestTransaction()
    {
        return $this->hasOne(Transanction::class, 'payer_id')->latest();
    }
}

app/Http/Controllers/Admin/TeacherController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TeacherRequest;
use App\Http\Requests\TrainerRequest;
use App\Models\SubAdmin;
use App\Models\Teacher;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class TeacherController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $data = Teacher::whereNull('deleted_at')->withCount('traineeGroups')->withCount('students')->withCount('quiz')
                ->orderBy('id','desc')->get();
            return view('admin.teacher.list', compact('data'));
        } catch (\Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('admin.teacher.create');
        } catch (\Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TrainerRequest $request)
    {
        try {
            $path = "default.png";
            if($request->hasFile('image')){
                SaveImageAllSizes($request, 'profile/');
                $path = 'profile/'.$request->image->hashName();
            }
            DB::beginTransaction();
            $data = [
                'name' => $request->name,
                'email' => $request->email,
                'is_active' => $request->status,
                'phone' => $request->phone,
                'gender' => $request->gender,
                'password' => bcrypt($request->password),
                'org_password' => $request->password,
                'profile_photo_path' => !empty($path) ? $path : "",
            ];
            Teacher::create($data);
            DB::commit();
            return redirect(route('teacher.index'))->with('success', 'Trainer added successfully.');

        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = Teacher::find($id);
            if ($data) {
                return view('admin.teacher.detail',compact('data'));
            } else {
                return Redirect::back()->withErrors('Sorry Trainer not found');
            }
        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        if(!empty($request->password)){
            $validated = $request->validate([
                'password_confirmation' => 'required|same:password',
            ]);
        }
        try {
            $data = Teacher::find($id);
            if ($data) {
                if($request->hasFile('profile_pic')){
                    UpdateImageAllSizes($request, 'profile/', $data->profile_photo_path);
                    $path = 'profile/'.$request->profile_pic->hashName();
                }
                DB::beginTransaction();
                $user_data = [
                    'name' => !empty($request->name) ? $request->name : $data->name,
                    'is_active' => !empty($request->status) ? $request->status : $data->is_active,
                    'phone' => !empty($request->phone) ? $request->phone : $data->phone,
                    'gender' => !empty($request->gender) ? $request->gender : $data->gender,
                    'password' => !empty($request->password) ? bcrypt($request->password) : $data->password,
                    'org_password' => !empty($request->password) ? $request->password : $data->password,
                    'profile_photo_path' => !empty($path) ? $path : $data->profile_photo_path,
                ];
                $data->update($user_data);
                DB::commit();
                return redirect(route('teacher.index'))->with('success', 'Trainer updated successfully.');
            } else {
                return Redirect::back()->withErrors(['Sorry student not found.']);
            }
        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $ques= Teacher::find($id);
            if ($ques) {
                $data = $ques->delete();
                return $this->apiResponse(JsonResponse::HTTP_OK, 'data', $data);
            } else {
                return $this->apiResponse(JsonResponse::HTTP_NOT_FOUND, 'message', 'Question not found');
            }

        } catch (\Exception $e) {
            DB::rollBack();
            return $this->apiResponse(JsonResponse::HTTP_INTERNAL_SERVER_ERROR, 'message', $e->getMessage());
        }
    }
}

resources/views/teacher/launchPaper/create.blade.php
@extends('teacher.layouts.main')
<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
@section('content')
    <div class="container-fluid">
        @if (session()->has('success'))
            <div class="alert alert-success">
                @if(is_array(session('success')))
                    <ul>
                        @foreach (session('success') as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </ul>
                @else
                    {{ session('success') }}
                @endif
            </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-12">
                <form id="LoginValidation" action="{{route('launch.store')}}" method="post" accept-charset="utf-8"
                      enctype="multipart/form-data">
                    @csrf
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">contacts</i>
                            </div>
                            <h4 class="card-title">Course specifics</h4>
                        </div>
                        <div class="card-body ">
                            <div class="row">

                                <input type="hidden" name="class_room" value="" id="trianee_group_name">
                                <input type="hidden" name="paper_id" value="" id="paper_id">

                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" name="start_datetime" placeholder="start date and time"
                                               class="form-control datetimepicker">
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <input type="text" name="end_datetime" placeholder="Expire date and time"
                                               class="form-control datetimepicker">
                                    </div>
                                </div>
                                <div class="col-md-2 mt-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Require Name </label>
                                        <input type="checkbox" name="setting[]" class="form-control"
                                               value="Require Name">
                                    </div>
                                </div>
                                {{--<div class="col-md-2 mt-4" >
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Shuffle Questions </label>
                                        <input type="checkbox" name="setting[]" class="form-control" value="Shuffle Questions">
                                    </div>
                                </div>
                                <div class="col-md-2 mt-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Shuffle Answers </label>
                                        <input type="checkbox" name="setting[]" class="form-control " value="Shuffle Answers">
                                    </div>
                                </div>
                                <div class="col-md-2 mt-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Show Feedback </label>
                                        <input type="checkbox" name="setting[]" class="form-control " value="Show Question Feedback">
                                    </div>
                                </div>--}}
                                <div class="col-md-2 mt-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Show Final Score </label>
                                        <input type="checkbox" name="setting[]" class="form-control "
                                               value="Show Final Score">
                                    </div>
                                </div>
                                {{-- <div class="col-md-2 mt-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Re Attempt </label>
                                        <input type="checkbox" name="setting[]" class="form-control "
                                               value="Re Attempt">
                                    </div>
                                </div> --}}
                            </div>
                        </div>
                        <input type="hidden" name="classroomurl" id="classroomurl" value="{{route('get.traine')}}">
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-rose">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary exampleModal" data-toggle="modal" data-target="#exampleModal"
            style="display: none">
        Trainee Group
    </button>
    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Trainee Group</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="col-md-12">
                        <div class="form-group">
                            <select class="form-control ClassRoom" id="class_room_id" aria-invalid="false"
                                    name="class_room_id">
                                @foreach($data as $room)
                                    <option value="{{$room->id}}">{{$room->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary nextbutton" data-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary traineeModel" data-toggle="modal" data-target="#courses"
            style="display: none">
        Course
    </button>
    <!-- Modal -->
    <div class="modal fade" id="courses" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Courses</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="col-md-12">
                        <div class="form-group">
                            <select class="form-control ClassRoom" id="courses" aria-invalid="false" name="courses">
                                @foreach($papers as $paper)
                                    <option value="{{$paper->id}}">{{$paper->name}}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary coursebutton" data-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>

@endsection
<script src="{{asset('public/assets/js/core/jquery.min.js')}}" type="text/javascript"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" type="text/javascript"></script>
<script>
    $(document).ready(function () {
        $('#exampleModal').modal('show');
    });
    $(document).on('click', '.nextbutton', function (e) {
        e.preventDefault();
        var class_room_id = $("#class_room_id option:selected").val();
        var trianee_group_name = $("#trianee_group_name").val(class_room_id);
        if (trianee_group_name) {
            $('#courses').modal('show');
        } else {
            toastr.warning('Please select Trainee group!')
        }
    });
    $(document).on('click', '.coursebutton', function (e) {
        e.preventDefault();
        var courses_id = $("#courses option:selected").val();
        var paper_id = $("#paper_id").val(courses_id);
    });
</script>