routes/web.php
Route::get('paypal', [\App\Http\Controllers\PaymentController::class,'getPaymentStatus'])->name('status');*/
/*==================paypal route===============*/
Route::get('/execute-payment', [\App\Http\Controllers\PaymentController::class,'execute']);
Route::post('/create-payment',[ \App\Http\Controllers\PaymentController::class,'create'])->name('create-payment');

Route::get('plan/create',[\App\Http\Controllers\SubscriptionController::class,'createPlan']);

Route::get('plan/list',[\App\Http\Controllers\SubscriptionController::class,'listPlan']);
Route::get('plan/{id}',[\App\Http\Controllers\SubscriptionController::class,'showPlan']);
Route::get('plan/{id}/activate',[\App\Http\Controllers\SubscriptionController::class,'activatePlan']);

Route::post('plan/{id}/agreement/create',[\App\Http\Controllers\SubscriptionController::class,'createAgreement'])->name('create-agreement');
Route::get('execute-agreement/{success}',[\App\Http\Controllers\SubscriptionController::class,'executeAgreement']);
/*==================paypal route===============*/

/*Route::get('payment', [\App\Http\Controllers\PayPalController::class,'payment'])->name('payment');
Route::get('cancel',  [\App\Http\Controllers\PayPalController::class,'cancel'])->name('payment.cancel');
Route::get('payment/success', [\App\Http\Controllers\PayPalController::class,'success'])->name('payment.success');*/

Route::get('/verify/{user}/{token}', [\App\Http\Controllers\Auth\RegisterController::class, 'verifyUser'])->name('verify');
Route::get('trianer/dashboard', [\App\Http\Controllers\Auth\RegisterController::class, 'trainerDashboard'])->name('trianer.dashboard');
Route::post('user/logout', [HomeController::class, 'logOutUser'])->name('logout.user');
Auth::routes();

Route::group(['prefix' => 'trainer'], function () {
    Route::get('/login', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'showLoginForm'])->name('teacher.login');
    Route::post('/login', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'TeacherLogin'])->name('teacher.login.submit');
    Route::post('/logout', [\App\Http\Controllers\Teacher\Auth\LoginController::class, 'logout'])->name('teacher.logout');
    Route::get('/register', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'showRegisterForm'])->name('teacher.register');
    Route::post('/register', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'TeacherRegister'])->name('teacher.register.store');
    Route::get('/V65Z2wb7qOFrwsBvJ2yxlxh6Cr99mXPAzdaRHJpFZO3N5isIyXzH9iCdWScM', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'basicPackage'])->name('basic.package');
    Route::get('/dbWuKajpRkewL6H79AStw3dhg57pCptYFSPdLqMi2KShbgzNYbcZKst10SkC', [\App\Http\Controllers\Teacher\Auth\RegisterController::class, 'premiumPackage'])->name('premium.package');
});

Route::group(['middleware' => ['auth:teacher'],'prefix' => 'trainer'], function () {
    Route::get('/', [TeacherHomeController::class, 'index'])->name('teacher.home');
    Route::get('/success', [TeacherHomeController::class, 'success'])->name('success');
    Route::get('/return', [TeacherHomeController::class, 'failure'])->name('failure');
    //Route::middleware([\App\Http\Middleware\Subscription::class])->group(function(){
        Route::resource('question', \App\Http\Controllers\Teacher\QuestionController::class);
        Route::resource('classrooms', \App\Http\Controllers\Teacher\ClassRoomController::class);
        Route::resource('students', StudentController::class);
        Route::get('all/trainee/{id}', [StudentController::class,'index'])->name('all.trainee');
        Route::get('create/trainee/{id}', [StudentController::class,'createTrainee'])->name('create.trainee');
        Route::get('edit/trainee/{id}', [StudentController::class,'editTrainee'])->name('edit.trainee');
        Route::post('save/trainee/{id}', [StudentController::class,'storeTrainee'])->name('save.trainee');
        Route::post('update/trainee/{id}', [StudentController::class,'updateTrainee'])->name('update.trainee');
        Route::delete('delete/trainee/{id}', [StudentController::class, 'destroy'])->name('trainer.trainee.destroy');
        Route::resource('quiz', PaperController::class);
        Route::get('/result', [PaperController::class, 'result'])->name('result.quiz');
        Route::get('/archive', [PaperController::class, 'archive'])->name('archive.quiz');
        Route::post('archive/status/{id}', [LaunchQuizController::class, 'QuizPutToArchive'])->name('putarchive');
        Route::post('archive/revert/{id}', [LaunchQuizController::class, 'archiveRevrt'])->name('archive.revert');
        Route::get('get/options', [PaperController::class, 'getQuestionOptions'])->name('getoption');
        Route::resource('launch', LaunchQuizController::class);
        Route::get('/quiz/attempt/{id}', [LaunchQuizController::class, 'attemptQuiz'])->name('quizattempt');
        Route::get('/course/result/{id}/{classroom}', [LaunchQuizController::class, 'trineeResult'])->name('trainee.result');
        Route::post('/course/end/{id}', [LaunchQuizController::class, 'courseEnd'])->name('course.end');
        Route::get('/course/result-table/{id}/{classroom}', [LaunchQuizController::class, 'trineeResultTable'])->name('trainee.resultTable');
        Route::get('/profile', [TeacherHomeController::class, 'editProfile'])->name('profile.edit');
        Route::post('/profile/edit', [TeacherHomeController::class, 'profileUpdate'])->name('profile.update');
        Route::get('/subscription/plan', [TeacherHomeController::class, 'subscriptionPlan'])->name('subs.plan');
        Route::get('get/trainee', [PaperController::class, 'getTrainee'])->name('get.traine');
    //});
});

Route::group(['prefix' => 'admin'], function () {
    Route::get('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'showLoginForm'])->name('admin.login');
    Route::post('/login', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'adminLogin'])->name('admin.login.submit');
    Route::post('/logout', [\App\Http\Controllers\Admin\Auth\LoginController::class, 'logout'])->name('admin.logout');
});

Route::group(['middleware' => ['auth:admin'], 'prefix' => 'admin'], function () {
    Route::get('/', [\App\Http\Controllers\Admin\HomeController::class, 'index'])->name('admin.home');
    Route::resource('subadmin', SubAdminController::class);
    Route::resource('teacher', \App\Http\Controllers\Admin\TeacherController::class);
    Route::get('/profile', [\App\Http\Controllers\Admin\HomeController::class, 'editProfile'])->name('admin.edit.profile');
    Route::post('/profile', [\App\Http\Controllers\Admin\HomeController::class, 'updateProfile'])->name('admin.update.profile');
    // for Students
    Route::resource('student', \App\Http\Controllers\Admin\StudentsController::class);
    Route::resource('classroom', \App\Http\Controllers\Admin\ClassRoomController::class);
    // for Students
    Route::get('/quiz', [\App\Http\Controllers\Admin\StudentController::class, 'papers'])->name('quiz.all');
    Route::get('/transaction', [\App\Http\Controllers\Admin\HomeController::class, 'transaction'])->name('transaction');
    Route::get('/packages', [\App\Http\Controllers\Admin\HomeController::class, 'packages'])->name('package');
    Route::post('update/packages', [\App\Http\Controllers\Admin\HomeController::class, 'updatePackages'])->name('update.package');
    Route::get('/launch/quiz', [\App\Http\Controllers\Admin\StudentController::class, 'launchPapers'])->name('admin.launch.quiz');
    Route::delete('/delete/paper', [\App\Http\Controllers\Admin\StudentController::class, 'deletePaper'])->name('admin.paper.destroy');
});

Route::group(['prefix' => 'subadmin'], function () {
    Route::get('/login', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'showLoginForm'])->name('subadmin.login');
    Route::post('/login', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'subAdminLogin'])->name('subadmin.login.submit');
    Route::post('/logout', [\App\Http\Controllers\SubAdmin\Auth\LoginController::class, 'logout'])->name('subadmin.logout');
    Route::get('/register', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'showRegisterForm'])->name('subadmin.register');
    Route::post('/register', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'subAdminRegister'])->name('subadmin.register.store');
    Route::post('/verify', [\App\Http\Controllers\SubAdmin\Auth\RegisterController::class, 'subAdminRegister'])->name('subadmin.register.verify');
});

Route::group(['middleware' => ['auth:subadmin'], 'prefix' => 'subadmin'], function () {
    Route::get('/', [\App\Http\Controllers\SubAdmin\HomeController::class, 'index'])->name('subadmin.home');
    Route::resource('teachers', \App\Http\Controllers\SubAdmin\TeacherController::class);
    Route::resource('all-class-rooms', \App\Http\Controllers\SubAdmin\ClassRoomController::class);
    Route::resource('all-students', \App\Http\Controllers\SubAdmin\StudentController::class);
    Route::get('/profile', [\App\Http\Controllers\SubAdmin\HomeController::class, 'editProfile'])->name('subadmin.edit.profile');
    Route::post('/profile', [\App\Http\Controllers\SubAdmin\HomeController::class, 'updateProfile'])->name('subadmin.update.profile');
});

Route::group(['prefix' => 'trainee'], function () {
    Route::post('/courseid', [TraineeController::class, 'courseId'])->name('courseid');
    Route::get('/traineeid/{id}', [TraineeController::class, 'getTraineeId'])->name('trainee.id');
    Route::post('/traineekey', [TraineeController::class, 'getTraineeKey'])->name('trainee.key');
    Route::post('/trainee/login', [TraineeController::class, 'TraineeLogin'])->name('trainee.login');
});
Route::group(['middleware' => ['auth', 'prevent-back-history'], 'prefix' => 'trainee'], function () {
    Route::get('/', [HomeController::class, 'startQuiz'])->name('home');

app/Models/ClassRoom.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;

class ClassRoom extends Model
{
    use Notifiable,HasFactory, SoftDeletes;
    protected $guarded = [];

    public function rooms() {
        return $this->hasManyThrough(ClassRoom::class,Teacher::class,'sub_admin_id','teacher_id');
    }
    public function teacher() {
        return $this->belongsTo(Teacher::class);
    }
    public function trtainee() {
        return $this->hasMany(User::class);
    }
}

app/Http/Controllers/Admin/ClassRoomController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\ClassRoom;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;

class ClassRoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        try {
            $data = ClassRoom::whereNull('deleted_at')->orderBy('id','desc')->get();
            return view('admin.classrooms.list', compact('data'));
        } catch (\Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        try {
            return view('admin.classrooms.create');
        } catch (\Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'name' => 'required',
            'class_code' => 'unique:class_rooms',
        ]);

        try {
            DB::beginTransaction();
            $class_data = [
                'name' => $request->name,
                'status' => $request->status,
                'class_code' => $request->class_code,
                'admin_id' => Auth::guard('admin')->user()->id,
            ];
            ClassRoom::create($class_data);
            DB::commit();
            return redirect(route('classroom.index'))->with('success', 'Class Room added successfully.');

        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        try {
            $data = ClassRoom::find($id);
            return view('admin.classrooms.detail',compact('data'));
        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        try {
            $data = ClassRoom::find($id);
            if ($data) {
                DB::beginTransaction();
                $cat_data = [
                    'status' => !empty($request->status) ? $request->status : $data->status,
                ];
                $data->update($cat_data);
                DB::commit();
                return redirect(route('classroom.index'))->with('success', 'Class room updated successfully.');
                //return Redirect::back()->with('success', 'Interest updated successfully.');
            } else {
                return Redirect::back()->withErrors(['Sorry Record not found.']);
            }

        } catch ( \Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        try {
            $ques= ClassRoom::find($id);
            if ($ques) {
                $data = $ques->delete();
                return $this->apiResponse(JsonResponse::HTTP_OK, 'data', $data);
            } else {
                return $this->apiResponse(JsonResponse::HTTP_NOT_FOUND, 'message', 'Question not found');
            }

        } catch (\Exception $e) {
            DB::rollBack();
            return $this->apiResponse(JsonResponse::HTTP_INTERNAL_SERVER_ERROR, 'message', $e->getMessage());
        }
    }
}

app/Http/Controllers/SubAdmin/ClassRoomController.php
<?php

namespace App\Http\Controllers\SubAdmin;

use App\Http\Controllers\Controller;
use App\Http\Requests\TeacherRequest;
use App\Models\ClassRoom;
use App\Models\SubAdmin;
use App\Models\Teacher;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Auth;


class ClassRoomController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        try {
            $current_id = Auth::guard('subadmin')->user()->id;
            $teacher_ids = Teacher::whereId($current_id)->whereIsActive('true')->whereNull('deleted_at')->pluck('id');
            $data = ClassRoom::whereNull('deleted_at')->whereIn('teacher_id',$teacher_ids)->orderBy('id','desc')->get();
            return view('subadmin.classrooms.list', compact('data'));
        } catch (\Exception $e) {
            DB::rollBack();
            return Redirect::back()->withErrors('Sorry something went wrong');
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/classrooms/create.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        @if (session()->has('success'))
            <div class="alert alert-success"> @if(is_array(session('success')))
                    <ul>
                        @foreach (session('success') as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </ul>
                @else
                    {{ session('success') }}
                @endif </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-12">
                <form id="LoginValidation" action="{{route('classroom.store')}}" method="post">
                    @csrf
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">contacts</i>
                            </div>
                            <h4 class="card-title">Class Room Form</h4>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Name *</label>
                                        <input type="text" class="form-control" id="name" required="true" name="name">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="examplePasswords" class="bmd-label-floating"> Class Code *</label>
                                        <input type="text" class="form-control" id="class_code" required="true" name="class_code">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <select name="status" id="status" class="form-control" required="true">
                                            <option value="Publish">Select Status</option>
                                            <option value="Publish">Publish</option>
                                            <option value="Unpublish">Unpublish</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-rose">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/classrooms/detail.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="container-fluid">
        @if (session()->has('success'))
            <div class="alert alert-success"> @if(is_array(session('success')))
                    <ul>
                        @foreach (session('success') as $message)
                            <li>{{ $message }}</li>
                        @endforeach
                    </ul>
                @else
                    {{ session('success') }}
                @endif </div>
        @endif
        @if ($errors->any())
            <div class="alert alert-danger">
                <ul>
                    @foreach ($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            </div>
        @endif
        <div class="row">
            <div class="col-md-12">
                <form id="LoginValidation" action="{{route('classroom.update',$data->id)}}" method="post">
                    @csrf
                    @method('PUT')
                    <div class="card ">
                        <div class="card-header card-header-rose card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">contacts</i>
                            </div>
                            <h4 class="card-title">Class Room Form</h4>
                        </div>
                        <div class="card-body ">
                            <div class="row">
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="exampleEmails" class="bmd-label-floating"> Name *</label>
                                        <input type="text" class="form-control" id="name" required="true" name="name" value="{{$data->name}}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="examplePasswords" class="bmd-label-floating"> Class Code *</label>
                                        <input type="text" class="form-control" id="class_code" required="true" name="class_code" value="{{$data->class_code}}">
                                    </div>
                                </div>
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <select class="form-control" aria-invalid="false" name="status" required>
                                            <option value="Publish" {{ ( $data->status == "Publish") ? 'selected' : '' }}>Publish</option>
                                            <option value="Unpublish" {{ ( $data->status == "Unpublish") ? 'selected' : '' }}>Unpublish</option>
                                        </select>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="card-footer ml-auto mr-auto">
                            <button type="submit" class="btn btn-rose">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/classrooms/list.blade.php
@extends('admin.layouts.main')
@section('content')
    <div class="content">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">
                    <div class="card">
                        <div class="card-header card-header-primary card-header-icon">
                            <div class="card-icon">
                                <i class="material-icons">assignment</i>
                            </div>
                            <h4 class="card-title">Trainee Groups</h4>
                        </div>
                        <div class="card-body">
                            <div class="toolbar">
                                <!--        Here you can write extra buttons/actions for the toolbar              -->
                            </div>
                            @if (session()->has('success'))
                                <div class="alert alert-success"> @if(is_array(session('success')))
                                        <ul>
                                            @foreach (session('success') as $message)
                                                <li>{{ $message }}</li>
                                            @endforeach
                                        </ul>
                                    @else
                                        {{ session('success') }}
                                    @endif </div>
                            @endif
                            @if ($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach ($errors->all() as $error)
                                            <li>{{ $error }}</li>
                                        @endforeach
                                    </ul>
                                </div>
                            @endif
                            <div class="material-datatables">
                                <table id="datatables" class="table table-striped table-no-bordered table-hover" cellspacing="0" width="100%" style="width:100%">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Trainer Name</th>
                                        <th>Trainee Group Code</th>
                                        <th>Status </th>
                                        <th>Created Date</th>
                                        <th class="disabled-sorting text-right">Actions</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Title</th>
                                        <th>Trainer Name</th>
                                        <th>Trainee Group Code</th>
                                        <th>Status </th>
                                        <th>Created Date</th>
                                        <th class="text-right">Actions</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>
                                    @if(!empty($data))
                                        @foreach($data as $row)
                                            <tr>
                                                <td>{{$row->id}} </td>
                                                <td>{{$row->name}} </td>
                                                <td>{{isset($row->teacher->name) ? $row->teacher->name : ""}} </td>
                                                <td>{{$row->class_code}} </td>
                                                <td>{{$row->status}}</td>
                                                <td>{{ $row->created_at->diffForHumans() }}</td>
                                                <td class="text-right">
{{--                                                    <a href="{{route('classroom.edit',$row->id)}}" class="btn btn-link btn-info btn-just-icon like"><i class="material-icons">edit</i></a>--}}
                                                    <a href="javascript:void(0)" class="btn btn-link btn-danger btn-just-icon remove" data-url="{{route('classroom.destroy',$row->id)}}"><i class="material-icons">close</i></a>
                                                </td>
                                            </tr>
                                        @endforeach
                                    @endif

                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <!-- end content-->
                    </div>
                    <!--  end card  -->
                </div>
                <!-- end col-md-12 -->
            </div>
            <!-- end row -->
        </div>
    </div>
@endsection
<script src="{{asset('public/assets/js/core/jquery.min.js')}}" type="text/javascript"></script>
<script>
    $(document).on('click','.remove',function (event) {
        event.preventDefault();
        swal({
            title: "Are you sure?",
            text: "Are you sure you want to delete.",
            icon: "warning",
            showCancelButton: true,
            buttons: {
                cancel: {
                    text: "Cancel",
                    value: null,
                    visible: true,
                    className: "btn-dark",
                    closeModal: false,
                },
                confirm: {
                    text: "Ok",
                    value: true,
                    visible: true,
                    className: "btn-dark",
                    closeModal: false
                }
            }
        }).then(isConfirm => {
           if (isConfirm) {
                $.ajaxSetup({
                    headers: {
                        'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                    }
                });
                var profile_url = $(this).attr("data-url");
                $.ajax({
                    type:'delete',
                    url:profile_url,
                    success: function (results) {
                        if (results.data) {
                            if (results.data == true){
                                swal("deleted!", "Trainee group deleted successfully.", "success");
                            } else {
                                swal("warning!", "Trainee group not deleted.", "warning");
                            }

                            location.reload();
                            //swal("Done!", results.message, "success");

                        } else {
                            swal("Error!", results.message, "error");
                        }
                    }
                });

            } else {
                swal("Cancelled","Record is safe.");
            }
        });
    });
</script>